language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
  - client/node_modules
install:
  - cd client && npm install
  - npm install
env:
    matrix:
      - TEST_SUITE=client
      - TEST_SUITE=server
script:
 - 'if [ $TEST_SUITE = "client" ]; then cd client && npm test; fi'
 - 'if [ $TEST_SUITE = "server" ]; then npm test; fi'
